hospital_project/config/routes.rb
Rails.application.routes.draw do

  devise_for :users

resources :hospitals do 
  resources :patients do
    resources :medications do
    end
    member do 
      put :wait
      put :check_up
      put :x_ray
      put :surgery
      put :pay
      put :discharge
    end
  end
end

 root 'hospitals#index'

end

hospital_project/app/models/patient.rb
class Patient < ActiveRecord::Base

    def full_name
      puts self.first_name

      puts self.last_name
    "#{self.first_name.downcase.capitalize} #{self.last_name.downcase.capitalize}"
    end

belongs_to :facilities_provider, :polymorphic => true
has_many :doctors, :as => :healthcare_recipient
has_many :medications

validates :first_name, presence: true
validates :last_name, presence: true
validates :malady, presence: true
# validates :date_of_birth, presence: true

  include Workflow
  workflow do

    state :waiting do
     event :check_up, transitions_to: :checked_up
     event :x_ray, transitions_to: :x_rayed
     event :get_surgery, transitions_to: :had_surgery
     event :discharge, transitions_to: :discharged
    end 
    
    state :checked_up do
     event :wait, transitions_to: :waiting
     event :x_ray, transitions_to: :x_rayed
     event :get_surgery, transitions_to: :had_surgery
     event :pay, transitions_to: :paid
    end

    state :x_rayed do
      event :wait, transitions_to: :waiting
      event :check_up, transitions_to: :checked_up
      event :get_surgery, transitions_to: :had_surgery
      event :pay, transitions_to: :paid
    end

    state :had_surgery do
      event :wait, transitions_to: :waiting
      event :check_up, transitions_to: :checked_up
      event :pay, transitions_to: :paid
    end

    state :paid do
      event :discharge, transitions_to: :discharged
    end
  end
end

hospital_project/app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_patient, only: [:show, :edit, :update, :destroy, :transition]

  before_action :find_hospital, only: [:show, :new, :create, :edit, :update, :destroy, :transition]

  def show
    @medications = Medication.all
    @patients = Patient.where("make LIKE ?", "%#{params[:q]}%")
  end

  def new
    @patient = Patient.new
  end

  def create
    @patient = @hospital.patients.new(patient_params)

    if @patient.save == true
      flash[:notice] = "Patient was successfully created"
      redirect_to hospital_path(@hospital, method: :get)
    else 
      flash[:error] = "Patient was not successfully created"
      render :new
    end
  end

  def edit
    @patient = Patient.find params[:id]

  end

  def update   
    @patient = Patient.find params[:id]
    if @patient.update_attributes patient_params
      redirect_to hospital_path(@hospital)
    else 
      render :edit
    end
  end

  def destroy
    @patients = Patient.find params[:id]
    @patients.delete
    redirect_to hospital_path(@hospital, method: :get)
  end

    def transition
    event = params[:event]+'!'
    @patient.send(event.to_sym)
    redirect_to patient_path(@patient)
  end

private

  def find_patient
    @patient = Patient.find(params[:id])
  end

  def find_hospital
    @hospital = Hospital.find(params[:hospital_id])
  end

  def patient_params
    params.require(:patient).permit(:first_name, :last_name, :malady, :gender, :date_of_birth, :workflow_state, :hospital_id)
  end
end

hospital_project/app/views/patients/_record_form.html.erb
<%= form_for [@hospital, @patient] do |x| %>
<!-- form_for is going to generate your action so you have to give it all of your routes. -->
  <div><% if x.object.errors.messages.length > 0 %>
    <% x.object.errors.messages.each do |key, value| %>
      <% value.each do |message| %>
        <%= key.capitalize %> <%= message %>
         <br>
      <% end %> 
    <% end %>
  <% end %>
    </div>

  <%= x.label :first_name, "First name:" %>
  <%= x.text_field :first_name %>
    <br>
  <%= x.label :last_name, "Last name:"%>
  <%= x.text_field :last_name %>
    <br>
  <%= x.label :malady, "Malady:" %>
  <%= x.text_field :malady %>
    <br>
    <%= x.label :workflow_state, "Status:" %>
    <%= x.text_field :workflow_state %>
    <!-- I need an options_for_select box here with all my possible statuses given the current state.(so maybe an if/then will also be necessary) It appears that the options_for_select function will be an easy way to select medications and link them to patients, because the parameters include the option value id which can correlate to another database object.
  -->
    <br>
  <%= x.label :gender, "Gender:"%>
  <%= x.radio_button :gender, 'Male', :checked => true %> 
  <%= label :gender_male, 'Male' %>
  <%= x.radio_button :gender, 'Female' %>
  <%= label :gender_female, 'Female' %>
    <br>
  <%= x.label :date_of_birth, "Date of birth" %>
  <%= x.date_select(:date_of_birth, start_year: 1800, end_year: 2014) %>
<!-- I don't want to have to update my code every year. How can i get these dates to change with the times? -->
    <br>
    <%=  %>
    <br>
    <%= x.submit "Save patient record", class: "squirrels" %>
<% end %>

  <br>
<%= link_to "Back to patient", hospital_patient_path(@hospital, @patient) %>
  <br>
  <%=  %>
  <br>
<%= link_to "Back to list of patients", hospital_path(@hospital, method: :get) %>

hospital_project/app/views/patients/show.html.erb
<h2>Patient Details</h2>
<br>
  <div class="row">
    <div class="col-sm-4 location col-sm-offset-4">
      <% if @patient.workflow_state == "waiting"  %>
        <div class="panel panel-default"> 
      <% elsif @patient.workflow_state == "checked_up" %>
        <div class="panel panel-primary"> 
      <% elsif @patient.workflow_state == "x_rayed" %>
        <div class="panel panel-warning">      
      <% elsif @patient.workflow_state == "had_surgery" %>
        <div class="panel panel-danger"> 
      <% elsif @patient.workflow_state == "paid" %>
        <div class="panel panel-success">  
      <% end %>

        <div class="panel-heading">
            <% full_name = @patient.first_name.try(:downcase).capitalize + " " + @patient.last_name.try(:downcase).capitalize %>
            <center><h3 class="panel-title"><%= full_name %></h3></center>
        </div>

        <div class="panel-body">
          <center>
            <label>Malady:</label>
            <%= @patient.malady.downcase.capitalize %> 
            <br>
            <label>Gender:</label>
            <%= @patient.gender %>
            <br>
            <label>Date of birth:</label>
            <%= @patient.date_of_birth %>
            <br>
            <label>Status:</label>
            <%= @patient.workflow_state %>
            <br>
            <label>Medications:</label>
            <% @patient.medications.each do |x| %>
              <br>
              <%= x.name %>
              <br>
              <%= x.description %>
              <br>
              <%= x.instructions %>
              <br>
              <%= link_to "Edit", edit_hospital_patient_medication_path(@hospital, @patient, x) %>
              <br>
            <% end %>
            <br>
            <label>Doctors:</label>
            <% @patient.doctors.each do |doctor| %>
              <%= doctor.first_name %>
              <%= doctor.last_name %>
            <% end %>
            <br>
            <br>
            <%= link_to "Add Medications", new_hospital_patient_medication_path(@hospital, @patient) %>
            <br>
            <%= link_to "Edit record", edit_hospital_patient_path(@hospital, @patient) %>
            <br>
            <br>
            <%= link_to "Destroy record", hospital_patient_path(@hospital, @patient), method: :delete %>
            <br>
            <br>
            <%= link_to "Back to list of patients", hospital_path(@hospital, method: :get) %>
            <br>
          </center>
        </div>
      </div> 
    </div>
  </div>           
    <br>