day1_rails_homework/config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

resources :patients
  root 'welcome#index'

end

day1_rails_homework/app/models/patient.rb
class Patient < ActiveRecord::Base
end

day1_rails_homework/app/controllers/patients_controller.rb
class PatientsController < ApplicationController

  def show
     @patient = Patient.find params[:id]
  end

  def new
    @patient = Patient.new

  end

  def create
    Patient.create patient_params
    redirect_to root_path

  end

  def edit
    @patient = Patient.find params[:id]
  end

  def update
    @patient = Patient.find params[:id]
    @patient.update_attributes patient_params
    redirect_to root_path
  end

  def destroy
    @patients = Patient.find params[:id]
    @patients.delete
    redirect_to root_path
  end

private
  def patient_params
    params.require(:patient).permit(:first_name, :last_name, :malady, :date_of_birth, :gender)
  end
end

day1_rails_homework/app/views/patients/_record_form.html.erb
<%= form_for @patient do |x| %>
    <%= x.label :first_name, "First name:" %>
    <%= x.text_field :first_name %>
  <br>
    <%= x.label :last_name, "Last name:"%>
    <%= x.text_field :last_name %>
  <br>
    <%= x.label :malady, "Malady:" %>
    <%= x.text_field :malady %>
  <br>
    <%= x.label :gender, "Gender:"%>
    <%= x.radio_button :gender, 'Male', :checked => true %> 
    <%= label :gender_male, 'Male' %>
    <%= x.radio_button :gender, 'Female' %>
    <%= label :gender_female, 'Female' %>
  <br>
    <%= x.label :date_of_birth, "Date of birth" %>
    <%= x.date_select(:date_of_birth, start_year: 1800, end_year: 2014) %>
<!-- I don't want to have to update my code every year. How can i get these dates to change with the times? -->
  <br>
    <%= x.submit "Save patient record" %>
<% end %>

  <br>

<%= link_to "Back", root_path %>

day1_rails_homework/app/views/welcome/index.html.erb
<h1>Patient records</h1>

<%= link_to 'Enter a new patient', new_patient_path %>

<ul>
  <% @patients.each do |x| %>
   <br>
   
    <% full_name = x.first_name.downcase.capitalize + " " + x.last_name.downcase.capitalize %>

   <li> 
     <label>Name:</label>
      <%=link_to full_name, patient_path(x) %>
   </li>

      <label>Malady:</label>
      <%= x.malady.downcase.capitalize %> 
    <br>

      <label>Gender:</label>
      <%= x.gender %>
    <br>

      <label>Date of birth:</label>
      <%= x.date_of_birth %>
    <br>

  <%= link_to "Edit record", edit_patient_path(x) %>
    <br>
  
  <%= link_to "Destroy record", patient_path(x), method: :delete %>
    <br>

  <% end %>
</ul>

<!-- sorry for the hideous formatting. I'll fix before the next submission -->