hospital_project/config/routes.rb
Rails.application.routes.draw do

  devise_for :users

resources :hospitals do 
  resources :patients do
    resources :medications do
    end
    member do 
      put :wait
      put :check_up
      put :x_ray
      put :surgery
      put :pay
      put :discharge
    end
  end
end

 root 'hospitals#index'

end

hospital_project/app/models/hospital.rb
class Hospital < ActiveRecord::Base
  has_many :patients, :as => :facilities_provider
  has_many :doctors, :as => :facilities_provider

  validates :name, presence: true

  # geocoded_by :full_street_address   # can also be an IP address
  # after_validation :geocode          # auto-fetch coordinates

  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode  # auto-fetch address

end



#relationship_type :object, 

hospital_project/app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController
  before_action :authenticate_user!
  def index
    @hospitals = Hospital.all
  end

  def show
    @hospital = Hospital.find params[:id]
    @patients = @hospital.patients
    @doctors = @hospital.doctors
  end

  def new
    @hospital = Hospital.new
  end

  def create
    @hospital = Hospital.new hospital_params
    if @hospital.save == true
      flash[:notice] = "Hospital was successfully created"
      redirect_to hospitals_path
    else 
      flash[:error] = "Hospital was not successfully created"
      render :new
    end
  end

  def edit
    @hospital = Hospital.find params[:id]
  end

  def update
    @hospital = Hospital.find params[:id]
    @hospital.update_attributes hospital_params
    redirect_to hospital_path(@hospital)
  end

  def destroy
    @hospital = Hospital.find params[:id]
    @hospital.delete
    redirect_to hospitals_path
  end

  private

  def hospital_params
    params.require(:hospital).permit(:name, :beds, :full_street_address)
  end

end

hospital_project/app/views/hospitals/_hospital_form.html.erb
<div><%= form_for [@hospital] do |x| %>
<!-- form_for is going to generate your action so you have to give it all of your routes. -->
<% if x.object.errors.messages.length > 0 %>
    <% x.object.errors.messages.each do |key, value| %>
      <% value.each do |message| %>
        <%= key.capitalize %> <%= message %>
         <br>
      <% end %> 
    <% end %>
  <% end %>
    </div>

  <%= x.label :name, " Name:" %>
  <%= x.text_field :name %>
    <br>
  <%= x.label :full_street_address, "Street Address:"%>
  <%= x.text_field :full_street_address %>
    <br>
  <%= x.label :city, "City:"%>
  <%= x.text_field :city %>
    <br>
  <%= x.label :state, "State:"%>
  <%= x.text_field :state %>
    <br>
  <%= x.label :zip, "Zip:"%>
  <%= x.text_field :zip %>
    <br>
  <%= x.label :beds, "Beds:" %>
  <%= x.text_field :beds %>
  
  <br>
    <%= x.submit "Save hospital" %>
<% end %></div>

  <br>

hospital_project/app/views/hospitals/index.html.erb
<h1>Locations</h1>
<br>

<!-- This link allows a user to build a new branch location, by redirecting them to our hospital form -->

<%= link_to 'Enter a new hospital', new_hospital_path(@hospital) %>
  <br>
  <br>

<!-- This nest of divs works with bootstrap to create tidy little panels where you display data you want to. I chose to display relevant information to my hospitals and allow a user to click on a location to see more details. These could be adapted to fit the needs of the user type such as doctors, patients, etc) -->

<div class="row">
  <% @hospitals.each do |x| %>
    <div class="col-sm-4 location">
      <div class="panel panel-info">
        <div class="panel-heading">
          <center><h3 class="panel-title"><%=link_to x.name, hospital_path(x) %></h3></center>
        </div>
        <div class="panel-body">
          <center>
          <label>Location:</label>
          <%= x.full_street_address %> 
          <br>
          <label>Beds:</label>
          <%= x.beds %>
          <br>
          <%= link_to "Edit hospital", edit_hospital_path(x) %>
          </center>
        </div>
      </div>
    </div>
  <% end %>
</div>
  <%= link_to "Log out", destroy_user_session_path, method: :delete %>
    <!-- I include the log out link on every page so that a user may end his or her session whenever they need to to -->
</ul>

hospital_project/app/views/hospitals/show.html.erb
<h1>Patient records</h1>
<!-- I want to put an A-Z and a search bar across the top -->
  <p><%= link_to 'Enter a new patient', new_hospital_patient_path(@hospital) %>
    <br>
  </p> 

<% total_patients = 0 %>

<!-- HIdden field. Will hold params[:hospital_id] as the value -->

<%= hidden_field_tag "", params[:id], class: 'hospital_id' %>
<%= text_field_tag '', '', class: "patient_search" %>
<%= link_to "Search patients", 'javascript:void(0);', class: "search_patients btn btn-md btn-primary" %>
<ul class="search_list"></ul>


<div class="col-lg-10 col-lg-offset-1">
  <table id="patients_table" class="tablesorter table-striped"> 
    <thead>
      <th>ID</th>
      <th>Name</th>
      <th>Malady</th>
      <th>Gender</th>
      <th>Status</th> 
    </thead> 
    <tbody>
    <% Patient.all.each_slice(5) do |y| %>       
    <% total_patients += 1 %>
      <% y.each do |z| %>
        <tr class="<%= 'hidden' if total_patients >= 2 %> slice_<%= total_patients %> the_patient">
          <td><%= z.id %></td>
          <td><%= link_to z.full_name, hospital_patient_path(@hospital, z) %></td>
          <td><%= z.malady %></td>
          <td><%= z.gender %></td>
          <td><%= z.workflow_state %></td>
        </tr>    
      <% end %>
    <% end %>  
    </tbody> 
  </table>          

<% total_patients.times do |q| %>
<%= link_to q + 1, "javascript:void(0);", class: "next_page" %>
<% end %>


<%= link_to "Back", hospitals_path(@hospital) %>
</ul>
  <br>

      <!-- workflow seems like a crappy way of branching logic. its not scalable because it doesn't mathematically define the relationships between states. You have to write gobs of logic. Instead, you could write a .each that corresponds to variables assigned to the ranges of allowable flows from one state to another, and pull your desired links out of an array when they match your criteria. This means you would write ONE loop, and then only have to input transitions into variable arrays that represent each state.(which would be very easy to copy and/or fill in ranges from one variable array to the next) 

    ...this is probably already built somewhere, just like the scaffold.
  -->